enable_disqus: false
enable_analytics: false
highlighter: rouge
permalink: pretty

#_url: http://localhost:4000
#_url: https://flaviomicheletti.github.io/git
_url: http://www.devfuria.com.br/git

secao: git

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"
